---

- name: Create /etc/openstack
  file:
    path: /etc/openstack
    state: directory
    owner: root
    group: root
    mode: '0400'

- name: Copy out clouds.yaml
  copy:
    src: "{{ openhpc_rebuild_clouds }}"
    dest: /etc/openstack/clouds.yaml
    owner: root
    group: root
    mode: '0400'
# TODO: warn/error if more than one entry?

- name: Setup slurm tools
  include_role:
    name: pytools

- name: Set slurm config parameters for openhpc role
  set_fact:
    openhpc_reboot_program: "{{ openhpc_rebuild_program }}"
    openhpc_reboot_from_controller: "{{ openhpc_rebuild_from_controller }}"
