---

- block:
    - name: Create /etc/openstack
      file:
        path: /etc/openstack
        state: directory
        owner: root
        group: root
        mode: '0400'
    - name: Copy out clouds.yaml
      copy:
        src: "{{ openhpc_rebuild_clouds }}"
        dest: /etc/openstack/clouds.yaml
        owner: root
        group: root
        mode: '0400'
    - name: Setup slurm tools
      include_role:
        name: pytools
  when: openhpc_enable.batch

- name: check for slurm.conf
  stat:
    path: /etc/slurm/slurm.conf
  register: slurm_conf

- name: add RebootProgram to slurm.conf
  lineinfile:
    path: "/etc/slurm/slurm.conf"
    regexp: "^RebootProgram=.*$"
    line: "RebootProgram=/opt/slurm-tools/bin/slurm-openstack-rebuild"
  when: slurm_conf.stat.exists

- name: reconfigure slurm
  shell:
    cmd: "scontrol reconfigure"
  when: openhpc_rebuild_reconfigure
  run_once: true
