- block:
  - stat:
      path: "{{ openhpc_rebuild_clouds }}"
    register: openhpc_clouds_path
  - name: Check clouds.yaml file openhpc_rebuild_clouds exists
    assert:
      that: openhpc_clouds_path.stat.exists
      fail_msg: "clouds.yaml file {{ openhpc_rebuild_clouds }} on localhost (specified by `openhpc_rebuild_clouds`) does not exist"
  delegate_to: localhost
  delegate_facts: true
  run_once: true
