- block:
  - stat:
      path: "{{ openhpc_rebuild_clouds }}"
    register: openhpc_clouds_path
  - name: Check OpenRC file (openhpc_rebuild_clouds) exists
    assert:
      that: openhpc_clouds_path.stat.exists
      fail_msg: "openrc file {{ openhpc_rebuild_clouds }} on localhost (specified by `openhpc_rebuild_clouds`) does not exist"
  - name: Check OpenRC file (openhpc_rebuild_clouds) is usable
    shell: |
      source {{ openhpc_rebuild_clouds }}
      openstack token issue
    changed_when: false
    no_log: True
  delegate_to: localhost
  delegate_facts: true
  run_once: true