---
- name: Create /etc/openstack
  file:
    path: /etc/openstack
    state: directory
    owner: slurm
    group: slurm
    mode: u=rX,go=

- name: Copy out clouds.yaml
  copy:
    src: "{{ autoscale_clouds }}"
    dest: /etc/openstack/clouds.yaml
    mode: u=r,go=
    owner: slurm
    group: slurm

- name: Setup Python/Slurm tools
  include_role:
    name: stackhpc.slurm_openstack_tools.pytools
  vars:
    pytools_user: slurm

- name: Modify openhpc_slurm_partitions
  set_fact:
    openhpc_slurm_partitions: "{{ openhpc_slurm_partitions | stackhpc.slurm_openstack_tools.modify_autoscale_partitions(openhpc_ram_multiplier) }}"
    
- name: Merge autoscale configuration
  set_fact:
    openhpc_config: "{{ autoscale_openhpc_config | combine(openhpc_config, list_merge='append') }}"
