---
- name: install python3
  package:
    name: python3,git

- name: Create virtualenv
  pip:
    name: git+https://github.com/stackhpc/slurm-openstack-tools.git
    virtualenv: /opt/slurm-tools
    virtualenv_command: python3 -m venv
  become: true
